version: '3.9'
services:
  app:
    build: .
    ports:
    - 8080:8080
    depends_on:
      - redis
      - mongodb
  redis:
    image: 'redis:alpine'
    restart: always
  mongodb:
    image: 'mongo:latest'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme
